/* ============================================================
   DAY 23 — SQL SERVER
   ALTER TABLE & CONSTRAINT MANAGEMENT
   ============================================================ */

-- ============================================================
-- 1. CREATE TABLE FOR PRACTICE
-- ============================================================

CREATE TABLE EMP77
(
    EMPNO INT,
    ENAME VARCHAR(10),
    SAL MONEY,
    EMAILID VARCHAR(50),
    DNO INT
);

-- Check table data
SELECT * FROM EMP77;


-- ============================================================
-- 2. INSERT SAMPLE DATA
-- ============================================================

INSERT INTO EMP77 VALUES
(100, 'A', 5000, 'a@gmail.com', 10),
(101, 'B', 4000, 'b@gmail.com', 20),
(102, 'C', 2500, 'c@gmail.com', 10),
(103, 'D', 3500, 'd@gmail.com', NULL);

SELECT * FROM EMP77;


-- ============================================================
-- 3. ADD CHECK CONSTRAINT
-- ============================================================

-- Salary must be greater than or equal to 3000

ALTER TABLE EMP77
ADD CHECK (SAL >= 3000);


-- NOTE:
-- This statement may fail because existing employee C
-- has salary 2500.

-- Check existing data
SELECT *
FROM EMP77
WHERE SAL < 3000;


-- ============================================================
-- 4. ADD CHECK CONSTRAINT WITH NOCHECK
-- ============================================================

-- Existing data will not be validated.

ALTER TABLE EMP77
WITH NOCHECK
ADD CHECK (SAL >= 3000);


-- Test new data

INSERT INTO EMP77
VALUES (104, 'E', 2000, 'e@gmail.com', 10);

-- The new invalid record should be rejected.


INSERT INTO EMP77
VALUES (105, 'F', 5000, 'f@gmail.com', 10);

-- Valid record should be accepted.


-- ============================================================
-- 5. CREATE DEPARTMENT TABLE
-- ============================================================

CREATE TABLE DEPT77
(
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(20)
);


INSERT INTO DEPT77 VALUES
(10, 'HR'),
(20, 'IT'),
(30, 'SALES');

SELECT * FROM DEPT77;


-- ============================================================
-- 6. ADD FOREIGN KEY
-- ============================================================

ALTER TABLE EMP77
ADD FOREIGN KEY (DNO)
REFERENCES DEPT77(DEPTNO);


-- Valid Foreign Key value

INSERT INTO EMP77
VALUES (106, 'G', 4000, 'g@gmail.com', 10);


-- Invalid Foreign Key value

INSERT INTO EMP77
VALUES (107, 'H', 4000, 'h@gmail.com', 99);

-- ERROR because 99 does not exist in DEPT77.


-- NULL is allowed in FK column

INSERT INTO EMP77
VALUES (108, 'I', 4000, 'i@gmail.com', NULL);


-- ============================================================
-- 7. ADD UNIQUE CONSTRAINT
-- ============================================================

ALTER TABLE EMP77
ADD UNIQUE (EMAILID);


-- Duplicate email should fail

INSERT INTO EMP77
VALUES (109, 'J', 4000, 'a@gmail.com', 10);


-- Unique email should work

INSERT INTO EMP77
VALUES (110, 'K', 4000, 'k@gmail.com', 20);


-- ============================================================
-- 8. ALTER COLUMN — NULL TO NOT NULL
-- ============================================================

-- First check NULL values

SELECT *
FROM EMP77
WHERE ENAME IS NULL;


-- Change ENAME to NOT NULL

ALTER TABLE EMP77
ALTER COLUMN ENAME VARCHAR(10) NOT NULL;


-- Test NULL value

INSERT INTO EMP77
VALUES (111, NULL, 4000, 'l@gmail.com', 10);

-- ERROR because ENAME is NOT NULL.


-- ============================================================
-- 9. ADD PRIMARY KEY
-- ============================================================

-- EMPNO must first be NOT NULL.

ALTER TABLE EMP77
ALTER COLUMN EMPNO INT NOT NULL;


-- Add Primary Key

ALTER TABLE EMP77
ADD PRIMARY KEY (EMPNO);


-- Test duplicate Primary Key

INSERT INTO EMP77
VALUES (100, 'X', 5000, 'x@gmail.com', 10);

-- ERROR because EMPNO 100 already exists.


-- ============================================================
-- 10. DROP CHECK CONSTRAINT
-- ============================================================

-- First find constraint names if required:

SELECT
    name,
    type_desc
FROM sys.objects
WHERE parent_object_id = OBJECT_ID('EMP77');


-- Example:

ALTER TABLE EMP77
DROP CONSTRAINT CK_EMP77_SAL;


-- NOTE:
-- Use the actual CHECK constraint name generated by SQL Server.


-- ============================================================
-- 11. DROP UNIQUE CONSTRAINT
-- ============================================================

-- Example:

ALTER TABLE EMP77
DROP CONSTRAINT UQ_EMP77_EMAILID;


-- NOTE:
-- Use the actual UNIQUE constraint name.


-- ============================================================
-- 12. CONSTRAINT DEPENDENCY PRACTICE
-- ============================================================

-- EMP77.DNO references DEPT77.DEPTNO.

-- Try dropping Primary Key:

ALTER TABLE DEPT77
DROP CONSTRAINT PK__DEPT77__;


-- This will fail if EMP77 has a Foreign Key
-- referencing DEPT77.DEPTNO.


-- ============================================================
-- 13. DROP FOREIGN KEY FIRST
-- ============================================================

-- Find the Foreign Key name:

SELECT
    name,
    type_desc
FROM sys.objects
WHERE parent_object_id = OBJECT_ID('EMP77');


-- Then drop the Foreign Key:

ALTER TABLE EMP77
DROP CONSTRAINT FK_EMP77_DEPT77;


-- Now Primary Key can be dropped if no other dependency exists.


-- ============================================================
-- 14. DROP PRIMARY KEY
-- ============================================================

ALTER TABLE DEPT77
DROP CONSTRAINT PK_DEPT77;


-- ============================================================
-- 15. DROP TABLE DEPENDENCY
-- ============================================================

-- If a Foreign Key references DEPT77,
-- dropping DEPT77 directly will fail.

DROP TABLE DEPT77;


-- Correct approach:
-- 1. Drop Foreign Key
-- 2. Drop Primary Key if required
-- 3. Drop Parent Table


-- ============================================================
-- 16. TRUNCATE TABLE DEPENDENCY
-- ============================================================

-- A referenced parent table cannot be truncated
-- while a Foreign Key dependency exists.

TRUNCATE TABLE DEPT77;


-- ============================================================
-- 17. FIND ALL CONSTRAINTS OF A TABLE
-- ============================================================

SELECT
    name AS ConstraintName,
    type_desc AS ConstraintType
FROM sys.objects
WHERE parent_object_id = OBJECT_ID('EMP77');


-- ============================================================
-- 18. PRACTICE SCENARIOS
-- ============================================================

/*
Q1. Add CHECK constraint:
    SAL >= 3000

Q2. Add CHECK constraint using WITH NOCHECK.

Q3. Add Foreign Key:
    EMP77.DNO -> DEPT77.DEPTNO

Q4. Add UNIQUE constraint on EMAILID.

Q5. Change ENAME from NULL to NOT NULL.

Q6. Add Primary Key on EMPNO.

Q7. Drop the CHECK constraint.

Q8. Drop the UNIQUE constraint.

Q9. Try dropping the parent Primary Key while
    Foreign Key dependency exists.

Q10. Try dropping the parent table while
     Foreign Key dependency exists.

Q11. Try truncating the parent table while
     Foreign Key dependency exists.
*/


-- ============================================================
-- 19. INTERVIEW PRACTICE
-- ============================================================

/*
1. What is WITH NOCHECK?

2. Does WITH NOCHECK validate existing rows?

3. Are new rows validated after adding a constraint
   WITH NOCHECK?

4. How do you add a Foreign Key to an existing table?

5. How do you add a UNIQUE constraint?

6. How do you change a nullable column to NOT NULL?

7. How do you remove a constraint?

8. Can a referenced Primary Key be dropped?

9. Can a referenced parent table be dropped?

10. Can a referenced parent table be truncated?

11. Why do Foreign Key dependencies affect DROP
    and TRUNCATE operations?
*/


-- ============================================================
-- DAY 23 QUICK REVISION
-- ============================================================

/*
WITH NOCHECK
    -> Existing data is not validated

ALTER TABLE
    -> Modify existing table

ADD CHECK
    -> Add validation rule

ADD FOREIGN KEY
    -> Establish relationship

ADD UNIQUE
    -> Prevent duplicates

ALTER COLUMN
    -> Modify column definition

DROP CONSTRAINT
    -> Remove constraint

PK + FK DEPENDENCY
    -> Restricts DROP / TRUNCATE

LEARN -> PRACTICE -> DOCUMENT -> IMPROVE
*/
